// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "hero": { "title": string; "instruction": string; "attribution": string } } };
  export const home: { "hero": { "title": string; "instruction": string; "attribution": string } };
}
