// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const home: { "hero": { "kicker": string; "headline": string; "subtitle": string; "ctaPrimary": string; "ctaSecondary": string }; "stats": Array<{ "id": string; "label": string; "value": number; "suffix": string }>; "cards": { "message": { "kicker": string; "title": string; "subtitle": string }; "vibe": { "kicker": string; "title": string }; "motion": { "kicker": string; "hint": string }; "origin": { "kicker": string; "title": string; "body": string; "highlight": string } }; "footer": { "line1": string; "line2": string } };
}
